### ISSUE TITLE
Generators is_numeric method error

### ISSUE THREAD

**Issue by ddamko** [rust-windowing/gl-rs#226]
I am receiving this error on compilation. Using cargo build with 0.13.0.nightly.

<code>generators/mod.rs:23:54: 23:66 error: type `char` does not implement any method in scope named `is_numeric`
generators/mod.rs:23     let ident = if (enm.ident.as_slice().char_at(0)).is_numeric() {
                                                                          ^~~~~~~~~~~~
error: aborting due to previous error
Could not compile `gl_generator`.</code>
